"""new fields in user model

Revision ID: 767eb7949d56
Revises: 558e16df00f7
Create Date: 2025-09-03 11:18:12.361258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767eb7949d56'
down_revision = '558e16df00f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
