"""Criação da tabela Reserva e tentativa de criação de um relacionamento entre User e Reserva

Revision ID: 66c610e96c78
Revises: 0b7ca7aa516a
Create Date: 2025-09-15 23:43:23.545204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c610e96c78'
down_revision = '0b7ca7aa516a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_telefone', sa.String(length=14), nullable=False),
    sa.Column('qtd_pessoas', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('mensagem', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_telefone'], ['user.telefone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserva_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_reserva_qtd_pessoas'), ['qtd_pessoas'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=14), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_telefone'), ['telefone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telefone'))
        batch_op.drop_column('telefone')

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserva_qtd_pessoas'))
        batch_op.drop_index(batch_op.f('ix_reserva_data'))

    op.drop_table('reserva')
    # ### end Alembic commands ###
